Bump steno to latest git revision
rocknsm/rpms pull request #9
Opened 2019-03-26 14:37 UTC by bndabbs

Also cleans up go dependency imports and fixes warning about build ID

2019-03-26 22:00 UTC, dcode requested changes
Please address the comments

2019-03-26 22:00 UTC, dcode commented on stenographer/stenographer.spec
> +Release:        2.%{builddate}git%{shortcommit0}%{?dist}
Actually, don't bump the epoch. The epoch is just there because the earliest stenographer RPMs didn't use a strictly increasing versioning. The `builddate` provides an inherent increasing version string. Technically, this is the first release of the given commit too, so that should probably stay 1. We rely on the date to provide a "version" and the shortcommit0 to provide a solid upstream reference.

2019-03-26 22:00 UTC, dcode commented on stenographer/stenographer.spec
> +rsync -az --exclude=src/ ./ src/github.com/google/%{name}
If you're going to use `rsync`, you need to add it to the BuildRequires

2019-03-27 11:35 UTC, bndabbs commented
Ready for another review @dcode

2019-03-27 16:45 UTC, dcode approved these changes

2019-03-27 16:45 UTC, merged